### ISSUE TITLE
Overview of test runs and interpretation of results

### ISSUE THREAD

**Issue by haakon-e** [haakon-e/mastersproject#14]
# Overview
This issue keeps track of test runs and potential issues in their results.

#### Key features
* Type: Contact Mechanics Biot
* Fractures: S1_2, S3_1
* Injection: 20 l/min to S1_2
* 4976 3d-cells, 104 2d-cells, 2 1d-cells
* Condition number `~2.5e+07`
* Location: `[...]/isc_modelling/results/200221/S1_2_S3_1/conv_u_p/injection_20lmin/default_n1__short_time_step`
#### Key results
* Some iterations did not converge on 20 newton iterations. However, they were close. 
    - Increase the number of newton iterations for each time step.
* Pressure is constant on the boundaries (either 0 or negative). This should be hydrostatic.
* No pressure source term is set. 
* The initial guess for pressure is set to 0. This is probably a big influence of slow convergence.
* The magnitudes for displacement are rather big (~10cm, etc.) for the 3D domain. This could be due to large domain, but also due to other errors.

**Comment by haakon-e** [comment]
## 2020-Feb-23
#### Key features
* method: `test_decomposition_of_stress`
* args: `hydrostatic`
* Type: Contact Mechanics
* Fractures: None
* 125 3d-cells, 
* Condition number `~1.0e+13`
* Location: `[...]/GTS/test/results/test_mechanics_class_methods/test_decomposition_of_stress/200223`
#### Key results
* Three test runs.
    1. Full stress tensor (`stress`)
    2. Hydrostatic stress (`trace(stress)/3`)
    3. Deviatoric stress (`stress - hydrostatic stress`)
* The displacements for cases 2 and 3 does not sum to the displacement for case 1
    - Perhaps this is expected?
* Case 1:
    - In paraview, we observe some rotation. It is difficult to see whether there has been net compression or not.
* Case 2:
    - In paraview, we clearly see compression of the specimen.
    - To be tested numerically: We do not want any rotation in this case.
* Case 3:
    - In paraview, we see rotation in the yz-plane (+), xz-plane (-). There is some rotation in xy-plane (+), however this is minimal.

**Comment by haakon-e** [comment]
## 2020-Feb-24
### Case 1
#### Key features
* method: `test_decomposition_of_stress`
* args: `'normal_shear'`
* Type: Contact Mechanics
* Fractures: None
* 125 3d-cells, 
* Condition number `~1.0e+13`
* Location: `[...]/GTS/test/results/test_mechanics_class_methods/test_decomposition_of_stress/200224/normal_shear`
* adjust stress for depth is turned *off* by commenting out the code.
#### Key results
* Three test runs.
    1. Full stress tensor
    2. normal stress (diagonal components)
    3. shear stress (off-diagonal components)
* The displacements for cases 2 and 3 does not sum to the displacement for case 1
    - Perhaps this is expected?
    - E.g. perhaphs boundary conditions matter?
    - Or perhaps the physics simply doesn't allow for additive solutions (check literature)
* Case 1:
    - In paraview, we observe some rotation. It is difficult to see whether there has been net compression or not.
    - `u_exp` magnitude: `[6.4e-03, 2.8e-02]`
* Case 2:
    - We see rotation of the specimen on similar order as the full stress tensor. This is not expected at all as we have no shear components.
    - We actually have slightly more shear dislocation (along x-axis) compared to the case 1.
* Case 3:
    - In paraview, we see rotation of the specimen, on similar magnitude as the full tensor.
    - There was however less compression compared to the full tensor.
#### TODO
- [ ] Debug the assembly method. Where do the observations from case 2 come from? 
_Remark_: Also, compare these results with the `'hydrostatic'` case (see above). Are there differences? Hypothesis: Could the heterogenity in the isotropic components influence the result? What about the condition number?
- [ ] Test the setup with scaling. Do we get different results? 
- [ ] What are optimal scaling parameters for this setup?

**Comment by haakon-e** [comment]
## 2020-Feb-24
### Simulation 2
*Remark*: We are re-computing the above case, but we turn off the effects of gravity (source term). 
Recall that bc gravity scaling is still turned off.
#### Key features
* method: `test_decomposition_of_stress`
* args: `'normal_shear'`
* Type: Contact Mechanics
* Fractures: None
* 125 3d-cells, 
* Condition number `~1.0e+13`
* Location: `[...]/GTS/test/results/test_mechanics_class_methods/test_decomposition_of_stress/200224/no_gravity/normal_shear`
* adjust stress for depth is turned *off* by commenting out the code.
* mechanical source terms are set to *zero*. 
#### Key results
* Three test runs.
    - Full stress tensor
    - normal stress (diagonal components)
    - shear stress (off-diagonal components)
* Case 1 (full stress):
    - We observe higher magnitude of negative displacement on the left/west half of the cube (along the x-axis).
    - The cube is slanting/leaning towards the east face, especially along the top-east face.
    - The compression in the north-south direction (along y-axis) is relatively small. 
    - The compression along the east-west axis is relatively large on the west face, smaller on the east face towards bottom, and extensional on the east face towards top.
    - The compression along the top-bottom axis is relatively large along the top face, and almost zero along the bottom face. Note that the domain is clamped in three cells on the bottom (on this coarse grid, these cells are relatively large. Total 16 cells on bottom face).

*Remarks*: One question above (Simulation 1) pertains to the observation that displacements seem heterogenous along e.g. the bottom face. We hypothesise that this is due to non-symmetries in the choice of which three faces are clamped, in combination with the presence of a gravity term.

* Case 2 (normal stress)
    - `u_exp: [1.6e-03, 9.0e-03]`
    - Uniform compression along each horizontal axis. east-west face has more compression compared to north-south. This is because the isotropic stress component in that direction is larger (by a factor of ~30%). The vertical displacement is larger on the top face compared to the east-west face. The bottom face is clamped in three points, which results in almost no displacement on that face. 
    - Although the x-axis stress is larger than the z-axis stress, we observe larger displacement of the top face compared to the east and west faces
